# Generated by Django 4.2.5 on 2024-02-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('hostel_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('machine_model', models.CharField(blank=True, max_length=255, null=True)),
                ('problem_description', models.TextField()),
            ],
        ),
    ]
